--- 
rubyforge_project: linguistics
project_requirements: {}

project_description: |-
  in any language. It includes a generic language-independant front end, a
  module for mapping language codes into language names, and a module which
  contains various English-language utilities.
rubyforge_group: deveiate
author_name: Michael Granger
project_homepage: http://deveiate.org/projects/Linguistics/
project_dependencies: {}

project_summary: a framework for building linguistic utilities for Ruby objects
project_name: Linguistics
version_file: linguistics.rb
additional_pkgfiles: 
- examples/*.rb
- README.english
dev_dependencies: 
  wordnet: ">=1.0.5"
  linkparser: ">=1.0.2"
author_email: ged@FaerieMUD.org
